- name: Upgrade apt
  apt:
    upgrade: yes

- name: Install general package
  apt:
    pkg:
    - software-properties-common
    - python3
    - python3-pip

- name: Install boto3
  pip:
    name: boto3
