- name: Create S3 bucket
  amazon.aws.s3_bucket:
     name: zenitech-paulgasp
     state: present
     policy: "{{ lookup('file', 'policy.json') }}"
     public_access:
         BlockPublicAcls:false

