- name: Create S3 bucket
  amazon.aws.s3_bucket:
     name: "{{ BUCKET_NAME }}"
     aws_access_key: "{{ AWS_ACCESS_KEY }}"
     aws_secret_key: "{{ AWS_SECRET_KEY }}"
     state: present
     policy: "{{ lookup('file', 'policy.json') }}"
     versioning: no
     tags:
       name: "{{ BUCKET_NAME }}"
       type: "E2"
     vars_files:
       - vars/main.yml
   register: s3_url

- name: Display s3 url
  debug: var=s3_url.stdout
